### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by billbrach** [slashmais/simplebup#3]
Debian 7, trying to compile. 'make clean' is ok, 'make' fails with this output:

g++ -Wall -pthread -c main.cpp
main.cpp: In function ‘int main(int, char*_)’:
main.cpp:98:21: error: ‘isatty’ was not declared in this scope
main.cpp:145:11: error: ‘sleep’ was not declared in this scope
make: *_\* [main.o] Error 1

I suspect missing dependencies.  If that's it, might want to add them to the README file.

**Comment by slashmais** [comment]
Thank you @billbrach

main.cpp needs to have

#include <unistd.h>

added to the list of includes.

It's been a while since I accessed GitHub, lost my keys, etc, will
need to find out how I can get back in to fix this ...

**Comment by slashmais** [comment]
Reason for: ‘isatty’/'sleep' .. was not declared in this scope -
errors is that unistd.h is no longer included in libstdc++, and has to
be explicitly included - since gcc 4.7
