### ISSUE TITLE
Another Compile Error

### ISSUE THREAD

**Issue by Thread7** [slashmais/simplebup#4]
I initially received the errors described in the previous "Compile Error" issue listed here.  But after adding the line: #include "unistd.h"
I now get this error: 
simplebup.cpp: In member function ‘void simplebup::StopAll()’:
simplebup.cpp:100:18: error: ‘close’ was not declared in this scope
   close(fdInotify);

I am not a cpp programmer so any suggestions would be appreciated.

**Comment by slashmais** [comment]
Hi,
I've fixed known bugs in my copy of this app, but is yet
to update GitHub with the latest sources.

I've also renamed the app to 'rtbup' (for RealTime BackUP).

You can monitor the GitHub project for when I've updated it,
or I can send you an email to tell you - let me know if you
want me to.

(May take a few days, me & the GitHub interface are not best of friends.. :)
